import React, { useEffect, useState } from 'react';
import { Wallet, CheckCircle2, AlertTriangle, Phone, MapPin, ShieldCheck, LockKeyhole, UserPlus, LogIn, X, RefreshCw, ShoppingBag, User, Save, LogOut } from 'lucide-react';
import { api, toman, dateFa, statusFa } from './shared.js';

export function AuthModal({onClose,onAuthed,adminOnly=false}){
  const [mode,setMode]=useState('login'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const body=mode==='register'?{name:f.get('name'),email:f.get('email'),phone:f.get('phone'),password:f.get('password')}:{identity:f.get('identity'),password:f.get('password')};const d=await api(`/api/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});if(adminOnly&&d.user.role!=='admin'){await api('/api/auth/logout',{method:'POST'});throw new Error('این حساب دسترسی مدیریت ندارد.');}onAuthed(d.user);}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose?.()}><div className="auth-card"><button className="modal-close" onClick={onClose}><X/></button><div className="auth-logo">SJ</div><h2>{adminOnly?'ورود مدیر':mode==='login'?'ورود به حساب':'ساخت حساب کاربری'}</h2><p>{adminOnly?'فقط حساب دارای نقش مدیر امکان ورود دارد.':'سفارش‌ها و وضعیت خریدهایت را از حساب کاربری پیگیری کن.'}</p>{error&&<div className="form-error"><AlertTriangle/> {error}</div>}<form onSubmit={submit}>{mode==='register'&&<><label>نام و نام خانوادگی<input name="name" required minLength="2" autoComplete="name"/></label><label>شماره موبایل<input name="phone" placeholder="0912..." autoComplete="tel"/></label><label>ایمیل<input name="email" type="email" required autoComplete="email"/></label></>}{mode==='login'&&<label>ایمیل یا شماره موبایل<input name="identity" required autoComplete="username"/></label>}<label>رمز عبور<input name="password" type="password" required minLength="8" autoComplete={mode==='login'?'current-password':'new-password'}/></label><button className="primary auth-submit" disabled={busy}>{busy?<RefreshCw className="spin"/>:mode==='login'?<LogIn/>:<UserPlus/>}{mode==='login'?'ورود':'ثبت‌نام'}</button></form>{!adminOnly&&<button className="auth-switch" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'حساب نداری؟ ثبت‌نام کن':'حساب داری؟ وارد شو'}</button>}</div></div>;
}

export function Checkout({cart,user,onNeedAuth,publicConfig,onSuccess,notify}){
  const [busy,setBusy]=useState(false),[coupon,setCoupon]=useState(''),[quote,setQuote]=useState(null),[error,setError]=useState('');
  const subtotal=cart.reduce((a,b)=>a+b.price*b.qty,0);
  const items=cart.map(i=>({productId:i.id,quantity:i.qty}));
  const applyCoupon=async()=>{if(!user)return onNeedAuth();try{const d=await api('/api/orders/quote',{method:'POST',body:JSON.stringify({items,couponCode:coupon})});setQuote(d);notify('تخفیف اعمال شد')}catch(e){setError(e.message)}};
  const submit=async e=>{e.preventDefault();if(!user)return onNeedAuth();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const created=await api('/api/orders',{method:'POST',body:JSON.stringify({items,couponCode:coupon,receiverName:f.get('name'),receiverPhone:f.get('phone'),province:f.get('province'),city:f.get('city'),address:f.get('address'),postalCode:f.get('postal'),shippingMethod:f.get('shipping'),notes:f.get('notes')})});const payment=await api('/api/payments/start',{method:'POST',body:JSON.stringify({orderId:created.order.id})});if(payment.redirectUrl){location.href=payment.redirectUrl;return;}onSuccess({order:payment.orderId,ref:payment.refId,mode:payment.mode});}catch(e){setError(e.message)}finally{setBusy(false)}};
  if(!cart.length)return <main className="inner empty"><ShoppingBag/><h2>سبد خرید خالی است</h2></main>;
  return <main className="inner checkout"><div className="page-title"><span>تکمیل سفارش</span><h1>اطلاعات ارسال و پرداخت</h1><p>{publicConfig.isSandboxMode?'حالت تست فعال است؛ پرداخت بانکی واقعی انجام نمی‌شود.':'پس از ثبت سفارش به درگاه زرین‌پال منتقل می‌شوید.'}</p></div>{!user&&<div className="login-required"><LockKeyhole/><div><b>برای ثبت سفارش وارد حساب شوید</b><span>سبد خریدت حفظ می‌شود.</span></div><button className="primary" onClick={onNeedAuth}>ورود / ثبت‌نام</button></div>}<div className="checkout-grid"><form onSubmit={submit}><h3>مشخصات تحویل‌گیرنده</h3>{error&&<div className="form-error"><AlertTriangle/> {error}</div>}<div className="form-grid"><label>نام و نام خانوادگی<input name="name" required defaultValue={user?.name||''}/></label><label>شماره موبایل<input name="phone" required defaultValue={user?.phone||''} placeholder="0912..."/></label><label>استان<input name="province" placeholder="قم"/></label><label>شهر<input name="city" required placeholder="قم"/></label><label className="full">آدرس کامل<textarea name="address" required minLength="8"/></label><label>کد پستی<input name="postal"/></label><label>روش ارسال<select name="shipping"><option value="post">پست / تیپاکس</option><option value="courier">پیک داخل شهر</option><option value="pickup">تحویل حضوری</option></select></label><label className="full">توضیحات سفارش<textarea name="notes" placeholder="اختیاری"/></label></div><h3>کد تخفیف</h3><div className="coupon-row"><input value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} placeholder="کد تخفیف"/><button type="button" onClick={applyCoupon}>اعمال</button></div><h3>روش پرداخت</h3><label className="payment active"><Wallet/><span><b>{publicConfig.isSandboxMode?'پرداخت تستی داخلی':'درگاه امن زرین‌پال'}</b><small>{publicConfig.isSandboxMode?'بدون کسر وجه؛ مناسب تست کامل سفارش':'تأیید تراکنش فقط روی سرور انجام می‌شود'}</small></span><i>✓</i></label><button className="primary full-btn" disabled={busy||!user}>{busy?<RefreshCw className="spin"/>:<Wallet/>}{publicConfig.isSandboxMode?'ثبت و پرداخت تستی':'رفتن به درگاه پرداخت'}</button></form><aside className="summary"><h3>سفارش ({cart.reduce((a,b)=>a+b.qty,0)} کالا)</h3>{cart.map(i=><p key={i.id}><span>{i.title} × {i.qty}</span><b>{toman(i.price*i.qty)}</b></p>)}<hr/><p><span>جمع کالاها</span><b>{toman(quote?.subtotal??subtotal)}</b></p>{quote?.discount>0&&<p><span>تخفیف</span><b className="green">- {toman(quote.discount)}</b></p>}<p><span>ارسال</span><b>{quote?toman(quote.shipping):'پس از ثبت'}</b></p><p className="sum"><span>مبلغ نهایی</span><b>{quote?toman(quote.total):toman(subtotal)}</b></p></aside></div></main>;
}

export function PaymentResult({result,go}){const ok=result?.ok;return <main className={'inner success '+(ok?'':'failure')}>{ok?<CheckCircle2/>:<AlertTriangle/>}<h1>{ok?'پرداخت و ثبت سفارش موفق بود':'پرداخت تکمیل نشد'}</h1>{result?.order&&<p>شماره سفارش: #{result.order}</p>}{result?.ref&&<p>کد پیگیری پرداخت: {result.ref}</p>}<span>{ok?'سفارش وارد مرحله پردازش شد و از حساب کاربری قابل پیگیری است.':'اگر وجهی کسر شده باشد، پیش از هر اقدام وضعیت تراکنش را از پشتیبانی پیگیری کنید.'}</span><div className="result-actions"><button className="primary" onClick={()=>go(ok?'account':'cart')}>{ok?'مشاهده سفارش‌ها':'بازگشت به سبد'}</button><button className="ghost" onClick={()=>go('home')}>خانه</button></div></main>}

export function Account({user,setUser,logout,onNeedAuth,notify}){
  const [orders,setOrders]=useState([]),[busy,setBusy]=useState(false);
  useEffect(()=>{if(user)api('/api/orders/my').then(d=>setOrders(d.orders)).catch(()=>{});},[user]);
  if(!user)return <main className="inner account-empty"><User/><h1>حساب کاربری</h1><p>برای مشاهده سفارش‌ها وارد شوید.</p><button className="primary" onClick={onNeedAuth}>ورود / ثبت‌نام</button></main>;
  const save=async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const d=await api('/api/auth/profile',{method:'PATCH',body:JSON.stringify({name:f.get('name'),phone:f.get('phone')})});setUser(d.user);notify('پروفایل ذخیره شد')}catch(e){notify(e.message)}finally{setBusy(false)}};
  return <main className="inner account-page"><div className="page-title"><span>حساب من</span><h1>{user.name}</h1><p>{user.email}</p></div><div className="account-grid"><section className="panel-card"><h3>اطلاعات حساب</h3><form onSubmit={save}><label>نام<input name="name" defaultValue={user.name}/></label><label>موبایل<input name="phone" defaultValue={user.phone}/></label><label>ایمیل<input value={user.email} disabled/></label><button className="primary" disabled={busy}><Save/> ذخیره</button></form><button className="danger-link" onClick={logout}><LogOut/> خروج از حساب</button></section><section className="panel-card orders-card"><h3>سفارش‌های من</h3>{!orders.length?<div className="muted-box">هنوز سفارشی ثبت نکرده‌اید.</div>:orders.map(o=><div className="order-row" key={o.id}><div><b>{o.order_code}</b><span>{dateFa(o.created_at)}</span></div><div><span className={'status '+o.status}>{statusFa[o.status]||o.status}</span><b>{toman(o.total)}</b></div></div>)}</section></div></main>;
}

export function InfoPage({type}){const data={services:['نصب تخصصی و تمیز','از نصب هدلایت و لنز تا دودی، دزدگیر و سیستم‌های امنیتی؛ با ابزار حرفه‌ای و ضمانت اجرای اسپرت جاوید.'],about:['ما ماشین‌ها را متفاوت می‌بینیم','اسپرت جاوید از قلب قم، با عشق به خودرو و تمرکز بر کالای اصیل، تجربه‌ای مطمئن برای علاقه‌مندان خودرو می‌سازد.'],contact:['کنارت هستیم','قم، خیابان شهیدان حسنی، نبش ۱۸ — شنبه تا پنجشنبه از ساعت ۹ تا ۲۱']}[type];return <main className="inner info"><span>اسپرت جاوید</span><h1>{data[0]}</h1><p>{data[1]}</p><div className="info-cards"><div><Phone/><b>مشاوره و سفارش</b><p>۰۲۵-۳۲۵۰ ۱۸۱۸</p></div><div><MapPin/><b>فروشگاه حضوری</b><p>قم، شهیدان حسنی، نبش ۱۸</p></div><div><ShieldCheck/><b>ضمانت خدمات</b><p>نصب تخصصی و پشتیبانی واقعی</p></div></div></main>}

