import React, { useEffect, useState } from 'react';
import { LayoutDashboard, Package, ShoppingBag, Users, Tags, LogOut, BarChart3, RefreshCw, CircleDollarSign, TrendingUp, Boxes, ClipboardList, AlertTriangle, ArrowLeft, Car } from 'lucide-react';
import { api, toman, statusFa } from './shared.js';
import { AdminProducts, AdminOrders, AdminUsers, AdminCoupons, AdminReports } from './admin-panels.jsx';

export function Admin({user,setUser,onExit,notify}){
  const [tab,setTab]=useState('dash');
  const [admin,setAdmin]=useState(user?.role==='admin'?user:null);
  const [loading,setLoading]=useState(true);
  const [data,setData]=useState({});
  const load=async t=>{setLoading(true);try{let d;if(t==='dash')d=await api('/api/admin/dashboard');if(t==='products')d=await api('/api/admin/products');if(t==='orders')d=await api('/api/admin/orders');if(t==='users')d=await api('/api/admin/users');if(t==='coupons')d=await api('/api/admin/coupons');if(t==='reports')d=await api('/api/admin/reports/sales?days=30');setData(d||{});}catch(e){if(e.message.includes('ادمین')||e.message.includes('ورود'))setAdmin(null);else notify(e.message)}finally{setLoading(false)}};
  useEffect(()=>{if(admin)load(tab);else setLoading(false)},[admin,tab]);
  if(!admin)return <div className="admin-login-page"><div className="admin-access-denied"><AlertTriangle/><h2>دسترسی مدیریت فعال نیست</h2><p>برای ورود به پنل، ابتدا از بخش حساب کاربری سایت با حساب مدیر وارد شوید.</p><button className="primary" onClick={onExit}><ArrowLeft/> بازگشت به فروشگاه</button></div></div>;
  const adminLogout=async()=>{await api('/api/auth/logout',{method:'POST'});setAdmin(null);setUser(null);onExit()};
  return <div className="production-admin"><aside><div className="brand"><b>SJ</b><span><strong>اسپرت جاوید</strong><small>پنل مدیریت</small></span></div>{[['dash',LayoutDashboard,'داشبورد'],['products',Package,'محصولات'],['orders',ShoppingBag,'سفارش‌ها'],['users',Users,'مشتریان'],['coupons',Tags,'تخفیف‌ها'],['reports',BarChart3,'گزارش‌ها']].map(([id,I,t])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I/>{t}</button>)}<button className="logout" onClick={onExit}><Car/> فروشگاه</button><button className="logout danger" onClick={adminLogout}><LogOut/> خروج</button></aside><main><header><div><span>مدیریت یکپارچه فروشگاه</span><h2>سلام، {admin.name}</h2></div><button className="icon-refresh" onClick={()=>load(tab)}><RefreshCw className={loading?'spin':''}/></button></header>{loading?<div className="admin-loading"><RefreshCw className="spin"/> در حال دریافت اطلاعات...</div>:<>{tab==='dash'&&<AdminDashboard data={data}/>} {tab==='products'&&<AdminProducts data={data} reload={()=>load('products')} notify={notify}/>} {tab==='orders'&&<AdminOrders data={data} reload={()=>load('orders')} notify={notify}/>} {tab==='users'&&<AdminUsers data={data}/>} {tab==='coupons'&&<AdminCoupons data={data} reload={()=>load('coupons')} notify={notify}/>} {tab==='reports'&&<AdminReports data={data}/>}</>}</main></div>;
}

function Stat({icon:I,label,value,sub}){return <div className="admin-stat"><I/><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}
function AdminDashboard({data}){const s=data.stats||{};return <><div className="admin-stats"><Stat icon={CircleDollarSign} label="فروش کل" value={toman(s.revenue)}/><Stat icon={TrendingUp} label="فروش امروز" value={toman(s.todayRevenue)}/><Stat icon={ShoppingBag} label="سفارش‌ها" value={s.orders||0}/><Stat icon={Users} label="مشتریان" value={s.customers||0}/><Stat icon={Boxes} label="محصول فعال" value={s.products||0}/></div><div className="admin-two"><section className="admin-card"><h3><ClipboardList/> سفارش‌های اخیر</h3><div className="admin-table"><table><thead><tr><th>کد</th><th>گیرنده</th><th>وضعیت</th><th>مبلغ</th></tr></thead><tbody>{(data.recentOrders||[]).map(o=><tr key={o.id}><td>{o.order_code}</td><td>{o.receiver_name}</td><td><span className={'status '+o.status}>{statusFa[o.status]||o.status}</span></td><td>{toman(o.total)}</td></tr>)}</tbody></table></div></section><section className="admin-card"><h3><AlertTriangle/> کمبود موجودی</h3>{(data.lowStock||[]).length?(data.lowStock||[]).map(p=><div className="low-stock" key={p.id}><span><b>{p.title}</b><small>{p.sku}</small></span><strong>{p.stock} عدد</strong></div>):<div className="muted-box">موجودی بحرانی ندارید.</div>}</section></div></>}
