import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ShoppingBag,User,Heart,Sun,Moon,MapPin,Phone,ArrowLeft,Star,ShieldCheck,Truck,Headphones,Menu,X,SlidersHorizontal,Minus,Plus,Trash2,Package,LayoutDashboard,Users,Tags,LogOut,ChevronLeft,Car,CheckCircle2,Eye,Edit3,TrendingUp,Wallet,CircleDollarSign} from 'lucide-react';
import './styles.css';

const cats=[['همه','all','✦'],['چراغ و هدلایت','light','◉'],['دودی و شیشه','tint','◐'],['بال و بدنه','body','⌁'],['کف‌پوش و کابین','cabin','▦'],['اگزوز','exhaust','◎'],['امنیت و GPS','security','⌖'],['اکسسوری','accessory','◇']];
const products=[
 {id:1,title:'هدلایت لنزو V90 Pro',cat:'light',price:3480000,old:3890000,rating:4.9,stock:8,badge:'پرفروش',emoji:'💡',compat:'تمام خودروها',desc:'نور سفید یخی، فن توربو بی‌صدا، ضمانت ۱۸ ماهه'},
 {id:2,title:'لنز بای‌لد سه اینچ X7',cat:'light',price:6250000,old:7100000,rating:4.8,stock:4,badge:'ویژه',emoji:'🔘',compat:'پژو، دنا، سمند',desc:'خط کات حرفه‌ای، نور بالا و پایین یکپارچه'},
 {id:3,title:'دودی نانو سرامیک UV400',cat:'tint',price:1890000,old:2200000,rating:4.7,stock:14,badge:'نصب رایگان',emoji:'◼️',compat:'تمام خودروها',desc:'کاهش ۹۹٪ اشعه UV، دید شفاف از داخل'},
 {id:4,title:'بال اسپرت صندوق یونیورسال',cat:'body',price:2890000,old:null,rating:4.6,stock:6,badge:'جدید',emoji:'🏎️',compat:'دنا، پژو، ساینا',desc:'ABS درجه یک، رنگ مشکی پیانویی'},
 {id:5,title:'کف‌پوش پنج‌بعدی چرمی',cat:'cabin',price:2450000,old:2750000,rating:4.9,stock:11,badge:'محبوب',emoji:'▦',compat:'مدل خودرو انتخابی',desc:'قالب دقیق، ضدآب، لبه بلند و قابل شست‌وشو'},
 {id:6,title:'گیت اگزوز ریموت‌دار',cat:'exhaust',price:5700000,old:6200000,rating:4.8,stock:3,badge:'صدای قابل تنظیم',emoji:'🔥',compat:'تمام خودروها',desc:'ریموت دوحالته، استیل ضدزنگ، سایز ۲.۵ اینچ'},
 {id:7,title:'دزدگیر تصویری استیل‌میت',cat:'security',price:4980000,old:null,rating:4.7,stock:9,badge:'ضمانت اصالت',emoji:'🔐',compat:'تمام خودروها',desc:'ریموت تصویری، شوک‌سنسور و قفل کودک'},
 {id:8,title:'ردیاب GPS آهنربایی JX',cat:'security',price:3690000,old:4100000,rating:4.5,stock:7,badge:'شارژدهی ۳۰ روز',emoji:'📍',compat:'خودرو و موتورسیکلت',desc:'ردیابی آنلاین، هشدار حرکت و اپ فارسی'},
 {id:9,title:'کنسول وسط پریمیوم',cat:'cabin',price:1650000,old:1950000,rating:4.4,stock:16,badge:'ارسال امروز',emoji:'🕹️',compat:'پراید، تیبا، کوییک',desc:'روکش چرم، جالیوانی و محفظه مخفی'},
 {id:10,title:'کیت نورپردازی داخل کابین',cat:'accessory',price:1290000,old:1490000,rating:4.6,stock:21,badge:'اپلیکیشن‌دار',emoji:'🌈',compat:'تمام خودروها',desc:'۶۴ رنگ، موزیک‌سینک و کنترل موبایل'},
];
const toman=n=>new Intl.NumberFormat('fa-IR').format(n)+' تومان';

function App(){
 const [theme,setTheme]=useState(localStorage.theme||'dark'),[page,setPage]=useState('home'),[cat,setCat]=useState('all'),[query,setQuery]=useState(''),[cart,setCart]=useState([]),[fav,setFav]=useState([]),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[admin,setAdmin]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.theme=theme},[theme]);
 useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'})},[page]);
 const filtered=useMemo(()=>products.filter(p=>(cat==='all'||p.cat===cat)&&p.title.includes(query)),[cat,query]);
 const add=p=>{setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]});setToast('به سبد خرید اضافه شد');setTimeout(()=>setToast(''),1800)};
 const go=p=>{setPage(p);setMenu(false)};
 if(admin)return <Admin onExit={()=>{setAdmin(false);setPage('home')}}/>;
 return <div className="app">
  <div className="topbar"><span>ارسال رایگان سفارش‌های بالای ۵ میلیون تومان</span><span><MapPin size={14}/> قم، خیابان شهیدان حسنی، نبش ۱۸</span></div>
  <header><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><button className="brand" onClick={()=>go('home')}><b>SJ</b><span><strong>اسپرت جاوید</strong><small>SPORT CAR Javid</small></span></button>
   <div className={'nav '+(menu?'open':'')}><button onClick={()=>go('home')}>خانه</button><button onClick={()=>go('shop')}>فروشگاه</button><button onClick={()=>go('services')}>خدمات نصب</button><button onClick={()=>go('about')}>درباره ما</button><button onClick={()=>go('contact')}>تماس</button><button className="admin-link" onClick={()=>setAdmin(true)}>ورود به پنل ادمین</button></div>
   <div className="actions"><button onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label="تغییر تم">{theme==='dark'?<Sun/>:<Moon/>}</button><button><User/></button><button onClick={()=>go('cart')} className="cart"><ShoppingBag/><i>{cart.reduce((a,b)=>a+b.qty,0)}</i></button></div>
  </header>
  {page==='home'&&<Home go={go} setCat={setCat} add={add} fav={fav} setFav={setFav}/>} 
  {page==='shop'&&<Shop cat={cat} setCat={setCat} query={query} setQuery={setQuery} items={filtered} add={add} fav={fav} setFav={setFav}/>} 
  {page==='cart'&&<Cart cart={cart} setCart={setCart} go={go}/>} 
  {page==='checkout'&&<Checkout cart={cart} setCart={setCart} go={go}/>} 
  {page==='services'&&<InfoPage type="services"/>}{page==='about'&&<InfoPage type="about"/>}{page==='contact'&&<InfoPage type="contact"/>}
  <footer><div className="footer-brand"><div className="logo">SJ</div><h3>اسپرت جاوید</h3><p>تخصص، اصالت و هیجان برای خودروی شما</p></div><div><h4>دسترسی سریع</h4><button onClick={()=>go('shop')}>فروشگاه</button><button onClick={()=>go('services')}>خدمات نصب</button><button onClick={()=>setAdmin(true)}>پنل ادمین دمو</button></div><div><h4>تماس با ما</h4><p>قم، خیابان شهیدان حسنی، نبش ۱۸</p><p>۰۲۵-۳۲۵۰ ۱۸۱۸</p><p>شنبه تا پنجشنبه ۹ تا ۲۱</p></div><div><h4>خرید مطمئن</h4><div className="trust"><span>ضمانت<br/>اصالت</span><span>پرداخت<br/>امن</span></div></div><small className="copy">© ۱۴۰۵ اسپرت جاوید — نسخه نمایشی فروشگاه</small></footer>
  {toast&&<div className="toast"><CheckCircle2/> {toast}</div>}
 </div>
}

function Home({go,setCat,add,fav,setFav}){return <main>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">از خیابان تا پیست، متفاوت باش</span><h1>خودروت رو از<br/><em>معمولی بودن</em> نجات بده.</h1><p>جدیدترین تجهیزات اسپرت و اکسسوری خودرو با ضمانت اصالت، نصب تخصصی و ارسال سریع.</p><div><button className="primary" onClick={()=>go('shop')}>مشاهده محصولات <ArrowLeft/></button><button className="ghost" onClick={()=>go('services')}>رزرو نصب حضوری</button></div><div className="hero-stats"><span><b>+۱۲۰۰</b> مشتری راضی</span><span><b>+۳۵۰</b> محصول اصل</span><span><b>۴.۹</b> امتیاز کاربران</span></div></div><div className="hero-art"><div className="speed-lines"></div><div className="car-art">🏎️</div><span className="float-tag"><b>نصب تخصصی</b><small>توسط تیم اسپرت جاوید</small></span></div></section>
 <section className="benefits"><div><ShieldCheck/><span><b>ضمانت اصالت</b><small>کالای اصل و تست‌شده</small></span></div><div><Truck/><span><b>ارسال سریع</b><small>تحویل فوری در قم</small></span></div><div><Car/><span><b>نصب حرفه‌ای</b><small>در فروشگاه حضوری</small></span></div><div><Headphones/><span><b>مشاوره تخصصی</b><small>قبل و بعد از خرید</small></span></div></section>
 <section className="section"><Heading kicker="انتخاب سریع" title="برای ماشینت چی می‌خوای؟" action={()=>go('shop')}/><div className="cat-grid">{cats.slice(1).map((c,i)=><button key={c[1]} onClick={()=>{setCat(c[1]);go('shop')}}><span>{c[2]}</span><b>{c[0]}</b><small>{[24,18,13,31,11,16,42][i]} محصول</small><ArrowLeft/></button>)}</div></section>
 <section className="section hot"><Heading kicker="پیشنهادهای داغ" title="انتخاب حرفه‌ای‌ها" action={()=>go('shop')}/><div className="products">{products.slice(0,4).map(p=><Product key={p.id} p={p} add={add} fav={fav} setFav={setFav}/>)}</div></section>
 <section className="cta"><span>خدمات نصب در قم</span><h2>خریدت رو بسپار دست حرفه‌ای‌ها</h2><p>نصب هدلایت، لنز، دودی، سیستم امنیتی و تجهیزات اسپرت با ابزار تخصصی و ضمانت اجرا.</p><button onClick={()=>go('services')}>مشاهده خدمات <ArrowLeft/></button></section>
 </main>}
function Heading({kicker,title,action}){return <div className="heading"><div><span>{kicker}</span><h2>{title}</h2></div><button onClick={action}>مشاهده همه <ArrowLeft/></button></div>}
function Product({p,add,fav,setFav}){let is=fav.includes(p.id);return <article className="product"><div className="p-img"><span className="badge">{p.badge}</span><button onClick={()=>setFav(f=>is?f.filter(x=>x!==p.id):[...f,p.id])} className={is?'liked':''}><Heart fill={is?'currentColor':'none'}/></button><div>{p.emoji}</div></div><small>{p.compat}</small><h3>{p.title}</h3><p>{p.desc}</p><div className="rating"><Star fill="currentColor"/> {p.rating} <span>• موجودی {p.stock}</span></div><div className="price">{p.old&&<del>{toman(p.old)}</del>}<b>{toman(p.price)}</b></div><button className="add" onClick={()=>add(p)}><ShoppingBag/> افزودن به سبد</button></article>}
function Shop({cat,setCat,query,setQuery,items,add,fav,setFav}){return <main className="inner"><div className="page-title"><span>فروشگاه تخصصی</span><h1>تجهیزات اسپرت خودرو</h1><p>محصول مناسب خودرویت را سریع و مطمئن پیدا کن.</p></div><div className="shop-tools"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجو بین محصولات..."/></div><div className="chips">{cats.map(c=><button className={cat===c[1]?'active':''} onClick={()=>setCat(c[1])}>{c[0]}</button>)}</div><button className="filter"><SlidersHorizontal/> فیلتر پیشرفته</button></div><div className="result"><span>{items.length} محصول پیدا شد</span><select><option>پربازدیدترین</option><option>جدیدترین</option><option>ارزان‌ترین</option></select></div><div className="products store">{items.map(p=><Product key={p.id} p={p} add={add} fav={fav} setFav={setFav}/>)}</div></main>}
function Cart({cart,setCart,go}){let total=cart.reduce((a,b)=>a+b.price*b.qty,0);const qty=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+d)}:i));return <main className="inner cart-page"><div className="page-title"><span>سبد خرید</span><h1>سفارش شما</h1></div>{!cart.length?<div className="empty"><ShoppingBag/><h2>سبد خریدت خالیه</h2><button className="primary" onClick={()=>go('shop')}>رفتن به فروشگاه</button></div>:<div className="cart-layout"><div className="cart-list">{cart.map(i=><div className="cart-item"><div className="mini">{i.emoji}</div><div><h3>{i.title}</h3><small>{i.compat}</small><b>{toman(i.price)}</b></div><div className="quantity"><button onClick={()=>qty(i.id,-1)}><Minus/></button><span>{i.qty}</span><button onClick={()=>qty(i.id,1)}><Plus/></button></div><button className="remove" onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}><Trash2/></button></div>)}</div><aside className="summary"><h3>خلاصه سفارش</h3><p><span>جمع کالاها</span><b>{toman(total)}</b></p><p><span>ارسال</span><b className="green">رایگان</b></p><hr/><p className="sum"><span>مبلغ پرداخت</span><b>{toman(total)}</b></p><button className="primary" onClick={()=>go('checkout')}>ادامه و پرداخت <ArrowLeft/></button><small><ShieldCheck/> پرداخت امن و ضمانت بازگشت وجه</small></aside></div>}</main>}
function Checkout({cart,setCart,go}){const [done,setDone]=useState(false);if(done)return <main className="inner success"><CheckCircle2/><h1>سفارش آزمایشی ثبت شد!</h1><p>کد پیگیری: SJ-1405-1028</p><span>پرداخت در حالت آزمایشی انجام شده و هیچ مبلغی کسر نشده است.</span><button className="primary" onClick={()=>{setCart([]);go('home')}}>بازگشت به خانه</button></main>;return <main className="inner checkout"><div className="page-title"><span>تکمیل سفارش</span><h1>اطلاعات ارسال و پرداخت</h1></div><div className="checkout-grid"><form onSubmit={e=>{e.preventDefault();setDone(true)}}><h3>مشخصات تحویل‌گیرنده</h3><div className="form-grid"><label>نام و نام خانوادگی<input required placeholder="مثلاً شروین جاوید"/></label><label>شماره موبایل<input required placeholder="۰۹۱۲۱۲۳۴۵۶۷"/></label><label className="full">آدرس<input required placeholder="استان، شهر، خیابان، پلاک"/></label><label>کد پستی<input placeholder="۱۰ رقم"/></label><label>روش ارسال<select><option>پیک فوری قم</option><option>پست پیشتاز</option></select></label></div><h3>روش پرداخت</h3><label className="payment active"><Wallet/><span><b>درگاه پرداخت آزمایشی</b><small>شبیه‌سازی پرداخت امن بانکی</small></span><i>✓</i></label><button className="primary full-btn">پرداخت آزمایشی و ثبت سفارش</button></form><aside className="summary"><h3>سفارش ({cart.length} کالا)</h3>{cart.map(i=><p><span>{i.title} × {i.qty}</span><b>{toman(i.price*i.qty)}</b></p>)}<hr/><p className="sum"><span>مبلغ نهایی</span><b>{toman(cart.reduce((a,b)=>a+b.price*b.qty,0))}</b></p></aside></div></main>}
function InfoPage({type}){let data={services:['نصب تخصصی و تمیز','از نصب هدلایت و لنز تا دودی، دزدگیر و سیستم‌های امنیتی؛ با ابزار حرفه‌ای و ضمانت اجرای اسپرت جاوید.'],about:['ما ماشین‌ها را متفاوت می‌بینیم','اسپرت جاوید از قلب قم، با عشق به خودرو و تمرکز بر کالای اصیل، تجربه‌ای مطمئن برای علاقه‌مندان خودرو می‌سازد.'],contact:['کنارت هستیم','قم، خیابان شهیدان حسنی، نبش ۱۸ — شنبه تا پنجشنبه از ساعت ۹ تا ۲۱']}[type];return <main className="inner info"><span>اسپرت جاوید</span><h1>{data[0]}</h1><p>{data[1]}</p><div className="info-cards"><div><Phone/><b>مشاوره و سفارش</b><p>۰۲۵-۳۲۵۰ ۱۸۱۸</p></div><div><MapPin/><b>فروشگاه حضوری</b><p>قم، شهیدان حسنی، نبش ۱۸</p></div><div><ShieldCheck/><b>ضمانت خدمات</b><p>نصب تخصصی و پشتیبانی واقعی</p></div></div></main>}
function Admin({onExit}){const [tab,setTab]=useState('dash');return <div className="admin"><aside><div className="brand"><b>SJ</b><span><strong>اسپرت جاوید</strong><small>پنل مدیریت دمو</small></span></div>{[['dash',LayoutDashboard,'داشبورد'],['products',Package,'محصولات'],['orders',ShoppingBag,'سفارش‌ها'],['users',Users,'مشتریان'],['discount',Tags,'تخفیف‌ها']].map(([id,I,t])=><button className={tab===id?'active':''} onClick={()=>setTab(id)}><I/>{t}{id==='orders'&&<i>۵</i>}</button>)}<button className="logout" onClick={onExit}><LogOut/> بازگشت به فروشگاه</button></aside><main><header><div><span>شنبه، ۱۸ مرداد ۱۴۰۵</span><h2>سلام، مدیر اسپرت جاوید 👋</h2></div><div className="admin-user"><span>شروین جاوید<small>مدیر کل</small></span><b>SJ</b></div></header>{tab==='dash'&&<Dashboard/>}{tab==='products'&&<ProductsAdmin/>}{tab==='orders'&&<OrdersAdmin/>}{!['dash','products','orders'].includes(tab)&&<div className="admin-panel"><h2>بخش {tab==='users'?'مشتریان':'تخفیف‌ها'}</h2><p>این بخش در نسخه نمایشی آماده مدیریت و توسعه است.</p></div>}</main></div>}
function Dashboard(){return <><div className="metrics"><Metric icon={CircleDollarSign} title="فروش امروز" value="۱۸,۴۵۰,۰۰۰" delta="۱۲٪ رشد"/><Metric icon={ShoppingBag} title="سفارش جدید" value="۲۴" delta="۵ نیازمند بررسی"/><Metric icon={Users} title="مشتری جدید" value="۱۷" delta="۸٪ رشد"/><Metric icon={Package} title="کمبود موجودی" value="۶" delta="نیاز به اقدام"/></div><div className="admin-grid"><section className="admin-panel chart"><div><h3>گزارش فروش هفتگی</h3><span>۷۸,۲۰۰,۰۰۰ تومان</span></div><div className="bars">{[40,65,48,80,62,95,72].map((x,i)=><div><i style={{height:x+'%'}}></i><small>{['ش','ی','د','س','چ','پ','ج'][i]}</small></div>)}</div></section><section className="admin-panel"><h3>محصولات پرفروش</h3>{products.slice(0,4).map((p,i)=><div className="best"><span>{p.emoji}</span><p><b>{p.title}</b><small>{12-i*2} فروش</small></p><strong>{toman(p.price)}</strong></div>)}</section></div><section className="admin-panel orders"><h3>آخرین سفارش‌ها</h3><OrdersTable/></section></>}
function Metric({icon:I,title,value,delta}){return <div><span><I/></span><p>{title}<b>{value}</b><small>{delta}</small></p></div>}
function OrdersTable(){return <div className="table"><div className="tr head"><span>کد سفارش</span><span>مشتری</span><span>مبلغ</span><span>وضعیت</span><span>تاریخ</span></div>{[['SJ-1028','علی محمدی','۶,۲۵۰,۰۰۰','درحال آماده‌سازی'],['SJ-1027','رضا کریمی','۳,۴۸۰,۰۰۰','ارسال‌شده'],['SJ-1026','مریم احمدی','۴,۹۸۰,۰۰۰','تکمیل‌شده'],['SJ-1025','امیر رضایی','۱,۸۹۰,۰۰۰','در انتظار پرداخت']].map((r,i)=><div className="tr">{r.map((x,j)=><span className={j===3?'status s'+i:''}>{x}</span>)}<span>امروز</span></div>)}</div>}
function ProductsAdmin(){return <section className="admin-panel"><div className="panel-head"><div><h2>مدیریت محصولات</h2><p>{products.length} محصول نمونه</p></div><button className="primary"><Plus/> افزودن محصول</button></div><div className="table product-table"><div className="tr head"><span>محصول</span><span>دسته</span><span>قیمت</span><span>موجودی</span><span>عملیات</span></div>{products.map(p=><div className="tr"><span className="prod-name"><i>{p.emoji}</i>{p.title}</span><span>{cats.find(c=>c[1]===p.cat)?.[0]}</span><span>{toman(p.price)}</span><span className={p.stock<5?'low':''}>{p.stock} عدد</span><span><button><Eye/></button><button><Edit3/></button></span></div>)}</div></section>}
function OrdersAdmin(){return <section className="admin-panel"><div className="panel-head"><div><h2>مدیریت سفارش‌ها</h2><p>پیگیری و تغییر وضعیت سفارش‌ها</p></div></div><OrdersTable/></section>}
createRoot(document.getElementById('root')).render(<App/>);
