import React from 'react';
import { Search, ShoppingBag, Heart, ArrowLeft, Star, ShieldCheck, Truck, Car, Headphones, SlidersHorizontal, Minus, Plus, Trash2 } from 'lucide-react';
import { cats, toman } from './shared.js';

export function Home({products,go,setCat,add,fav,setFav}){
  const featured=products.filter(p=>p.featured).slice(0,4);
  return <main>
    <section className="hero"><div className="hero-copy"><span className="eyebrow">از خیابان تا پیست، متفاوت باش</span><h1>خودروت رو از<br/><em>معمولی بودن</em> نجات بده.</h1><p>تجهیزات اسپرت و اکسسوری خودرو با ضمانت اصالت، نصب تخصصی و ارسال سریع.</p><div><button className="primary" onClick={()=>go('shop')}>مشاهده محصولات <ArrowLeft/></button><button className="ghost" onClick={()=>go('services')}>رزرو نصب حضوری</button></div><div className="hero-stats"><span><b>خرید امن</b> پرداخت درگاه</span><span><b>موجودی واقعی</b> کنترل لحظه‌ای</span><span><b>پشتیبانی</b> قبل و بعد خرید</span></div></div><div className="hero-art"><div className="speed-lines"></div><div className="car-art">🏎️</div><span className="float-tag"><b>نصب تخصصی</b><small>توسط تیم اسپرت جاوید</small></span></div></section>
    <section className="benefits"><div><ShieldCheck/><span><b>ضمانت اصالت</b><small>کالای اصل و تست‌شده</small></span></div><div><Truck/><span><b>ارسال سریع</b><small>تحویل فوری در قم</small></span></div><div><Car/><span><b>نصب حرفه‌ای</b><small>در فروشگاه حضوری</small></span></div><div><Headphones/><span><b>مشاوره تخصصی</b><small>قبل و بعد از خرید</small></span></div></section>
    <section className="section"><Heading kicker="انتخاب سریع" title="برای ماشینت چی می‌خوای؟" action={()=>go('shop')}/><div className="cat-grid">{cats.slice(1).map(c=><button key={c[1]} onClick={()=>{setCat(c[1]);go('shop')}}><span>{c[2]}</span><b>{c[0]}</b><small>مشاهده محصولات</small><ArrowLeft/></button>)}</div></section>
    <section className="section hot"><Heading kicker="پیشنهادهای داغ" title="انتخاب حرفه‌ای‌ها" action={()=>go('shop')}/><div className="products">{featured.map(p=><Product key={p.id} p={p} add={add} fav={fav} setFav={setFav}/>)}</div></section>
    <section className="cta"><span>خدمات نصب در قم</span><h2>خریدت رو بسپار دست حرفه‌ای‌ها</h2><p>نصب هدلایت، لنز، دودی، سیستم امنیتی و تجهیزات اسپرت با ابزار تخصصی و ضمانت اجرا.</p><button onClick={()=>go('services')}>مشاهده خدمات <ArrowLeft/></button></section>
  </main>;
}
export function Heading({kicker,title,action}){return <div className="heading"><div><span>{kicker}</span><h2>{title}</h2></div><button onClick={action}>مشاهده همه <ArrowLeft/></button></div>}
export function Product({p,add,fav,setFav}){const liked=fav.includes(p.id);return <article className="product"><div className="p-img">{p.badge&&<span className="badge">{p.badge}</span>}<button onClick={()=>setFav(f=>liked?f.filter(x=>x!==p.id):[...f,p.id])} className={liked?'liked':''}><Heart fill={liked?'currentColor':'none'}/></button>{p.imageUrl?<img src={p.imageUrl} alt={p.title}/>:<div>{p.emoji}</div>}</div><small>{p.compat}</small><h3>{p.title}</h3><p>{p.desc}</p><div className="rating"><Star fill="currentColor"/> {p.rating} <span>• {p.stock>0?`موجودی ${p.stock}`:'ناموجود'}</span></div><div className="price">{p.oldPrice&&<del>{toman(p.oldPrice)}</del>}<b>{toman(p.price)}</b></div><button className="add" disabled={p.stock<=0} onClick={()=>add(p)}><ShoppingBag/> {p.stock>0?'افزودن به سبد':'ناموجود'}</button></article>}
export function Shop({cat,setCat,query,setQuery,items,add,fav,setFav}){return <main className="inner"><div className="page-title"><span>فروشگاه تخصصی</span><h1>تجهیزات اسپرت خودرو</h1><p>محصول مناسب خودرویت را سریع و مطمئن پیدا کن.</p></div><div className="shop-tools"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام محصول یا SKU..."/></div><div className="chips">{cats.map(c=><button key={c[1]} className={cat===c[1]?'active':''} onClick={()=>setCat(c[1])}>{c[0]}</button>)}</div><button className="filter"><SlidersHorizontal/> فیلتر</button></div><div className="result"><span>{items.length} محصول پیدا شد</span></div><div className="products store">{items.map(p=><Product key={p.id} p={p} add={add} fav={fav} setFav={setFav}/>)}</div>{!items.length&&<div className="empty"><Search/><h2>محصولی پیدا نشد</h2></div>}</main>}

export function Cart({cart,setCart,go}){
  const total=cart.reduce((a,b)=>a+b.price*b.qty,0);
  const qty=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:Math.max(1,Math.min(i.stock,i.qty+d))}:i));
  return <main className="inner cart-page"><div className="page-title"><span>سبد خرید</span><h1>سفارش شما</h1></div>{!cart.length?<div className="empty"><ShoppingBag/><h2>سبد خریدت خالیه</h2><button className="primary" onClick={()=>go('shop')}>رفتن به فروشگاه</button></div>:<div className="cart-layout"><div className="cart-list">{cart.map(i=><div className="cart-item" key={i.id}><div className="mini">{i.imageUrl?<img src={i.imageUrl} alt=""/>:i.emoji}</div><div><h3>{i.title}</h3><small>{i.compat}</small><b>{toman(i.price)}</b></div><div className="quantity"><button onClick={()=>qty(i.id,-1)}><Minus/></button><span>{i.qty}</span><button onClick={()=>qty(i.id,1)}><Plus/></button></div><button className="remove" onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}><Trash2/></button></div>)}</div><aside className="summary"><h3>خلاصه سفارش</h3><p><span>جمع کالاها</span><b>{toman(total)}</b></p><p><span>ارسال</span><b>در تسویه محاسبه می‌شود</b></p><hr/><p className="sum"><span>جمع فعلی</span><b>{toman(total)}</b></p><button className="primary" onClick={()=>go('checkout')}>ادامه و پرداخت <ArrowLeft/></button><small><ShieldCheck/> مبلغ نهایی سمت سرور و بر اساس موجودی واقعی محاسبه می‌شود</small></aside></div>}</main>;
}
